name: 'Build dotnet plugin using GitVersion'
on:
  workflow_call:
    inputs:
      package_id:
        required: true
        type: string
      plugin_sln:
        required: false
        type: string
        default: "*.sln"
      manifest:
        required: false
        type: string
        default: "manifest.json"
jobs:
  build:
    permissions:
      packages: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.2
        with:
          versionSpec: '6.0.x'

      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.1.2

      - name: Update manifest version
        id: manifest_version
        run: |
            echo "$( jq '.version = "${{ env.GitVersion_FullSemVer }}"' ${{ inputs.manifest }} )" > ${{ inputs.manifest }}

      - name: Build
        run: |
          # build
          dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text --name chorizite "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          dotnet restore ${{ inputs.plugin_sln }}
          dotnet build -c Release --no-restore "-p:PackageOutputPath=${{ github.workspace }};OutputPath=${{ github.workspace}}/bin/" ${{ inputs.plugin_sln }}

      - uses: actions/upload-artifact@v4
        with: 
          name: "${{ inputs.package_id }}.${{ env.GitVersion_FullSemVer }}.nupkg"
          path: "${{ github.workspace }}/${{ inputs.package_id }}.${{ env.GitVersion_FullSemVer }}.nupkg"

      - uses: actions/upload-artifact@v4
        with: 
          name: "${{ inputs.package_id }}.${{ env.GitVersion_FullSemVer }}.zip"
          path: "${{ github.workspace}}/bin/"
      
      - name: Push GitHub NuGet Package
        run: |
          dotnet nuget push "${{ github.workspace }}/${{ inputs.package_id }}.${{ env.GitVersion_FullSemVer }}.nupkg" --api-key ${{ github.token }} --source "chorizite"
